apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: geolocation
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: geolocation
        tier: backend
        track: stable  
    spec:
      containers:
        - env:
          image: 076892551558.dkr.ecr.us-east-1.amazonaws.com/jenkins:0.0.6-RELEASE
          name: geolocation
          ports:
            - name: http
              containerPort: 80
      restartPolicy: Always