apiVersion: v1
kind: Service
metadata:
  name: geo-service
spec:
  selector:
    app: geolocation
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8082
  type: LoadBalancer
...