apiVersion: v1
kind: Service
metadata:
  name: backend-cip-service
spec:
  selector:
    app: geolocation
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
    type: LoadBalancer